<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["dp_log", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create dp_log
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "dp_log/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldApplicationname" class="col-sm-2 control-label">ApplicationName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ApplicationName", "size" => 30, "class" => "form-control", "id" => "fieldApplicationname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSource" class="col-sm-2 control-label">Source</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Source", "size" => 30, "class" => "form-control", "id" => "fieldSource"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldInstanceid" class="col-sm-2 control-label">InstanceId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["InstanceId", "type" => "number", "class" => "form-control", "id" => "fieldInstanceid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMessage" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Message", "size" => 30, "class" => "form-control", "id" => "fieldMessage"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStacktrace" class="col-sm-2 control-label">StackTrace</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["StackTrace", "size" => 30, "class" => "form-control", "id" => "fieldStacktrace"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedon" class="col-sm-2 control-label">CreatedOn</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["CreatedOn", "size" => 30, "class" => "form-control", "id" => "fieldCreatedon"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
